### ISSUE TITLE
it doesn't seem to work

### ISSUE THREAD

**Issue by PxYu** [takuti/jekyll-lazy-tweet-embedding#2]
I try the steps. No error occurred but the url just shows as plain text in the pages. 

Do i need to install sth else?

**Comment by PxYu** [comment]
![qq20160705-0](https://cloud.githubusercontent.com/assets/16612275/16569518/f854b0dc-4269-11e6-804b-26034ad04785.png)
![qq20160705-1](https://cloud.githubusercontent.com/assets/16612275/16569519/fc75f0a4-4269-11e6-9df1-2417d75862cc.png)

this is what i did.
Is there sth wrong?

**Comment by takuti** [comment]
Hi @PuxuanYu, thanks for your report. 

I checked [your repository](https://github.com/PuxuanYu/PuxuanYu.github.io) and tried very similar rendering-related setting on my environment as:

```
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart

gems: ['jekyll-twitter-plugin']
```

However, there is no problem and the plugin actually works. Thus, the reason is NOT in kramdown setting and conflict with "jekyll-twitter-plugin".

Are there any error messages when you run the `jekyll` command?
